packages/wp-plugin/essentials/essentials.php
code review.
work on branch until we're both happy, then merge
=> refactor(update_plugins): code review

docs/6-forking.md
minor update of the forking docs
=> docs: update forking instructions to include branch options

.npmrc, scripts/wp-env-after-start.sh
only lightweight changes to `.npmrc` and generated `.vscode/settings.json`
this pr does not update any dependencies.
=> chore: updated pnpm  and vscode settings for improved vscode search experience

packages/wp-plugin/essentials/inc/dashboard/blocks/deep-links/config/strato.php
- Related Issue #
- Closes #
I have
=> update URLs in strato.php to use relative paths

packages/wp-plugin/essentials/inc/dashboard/editor.php, packages/wp-plugin/essentials/inc/dashboard/index.php
=> fix: move POST_TYPE_SLUG constant to dashboard index

packages/wp-plugin/essentials/inc/dashboard/blocks/quick-links/render.php, packages/wp-plugin/essentials/inc/dashboard/data/ionos/post_content.html, packages/wp-plugin/essentials/inc/dashboard/data/ionos/rendered-skeleton.html
Changing position of row containing deep-links with the row containing quick-links.
- Related Issue: MR #143
I have
before:
after:
=> move content

packages/docker/rector-php/rector-config-php7.4.php, packages/docker/rector-php/rector-fix-types.php, packages/wp-plugin/essentials/essentials.php, packages/wp-plugin/essentials/inc/dashboard/blocks/banner/index.php, packages/wp-plugin/essentials/inc/dashboard/blocks/deep-links/index.php, packages/wp-plugin/essentials/inc/dashboard/blocks/quick-links/render.php, packages/wp-plugin/essentials/inc/dashboard/blocks/vulnerability/render.php, packages/wp-plugin/essentials/inc/dashboard/editor.php, packages/wp-plugin/essentials/inc/migration/index.php, packages/wp-plugin/essentials/inc/switch-page/view.php, packages/wp-plugin/essentials/languages/ionos-essentials-de_DE.po, packages/wp-plugin/essentials/languages/ionos-essentials-de_DE_formal.po, packages/wp-plugin/essentials/languages/ionos-essentials-en_US.po, packages/wp-plugin/essentials/languages/ionos-essentials-es_ES.po, packages/wp-plugin/essentials/languages/ionos-essentials-fr_FR.po, packages/wp-plugin/essentials/languages/ionos-essentials-it_IT.po, packages/wp-plugin/essentials/languages/ionos-essentials-nl_NL.po, packages/wp-plugin/essentials/languages/ionos-essentials-pl_PL.po, packages/wp-plugin/essentials/languages/ionos-essentials-sv_SE.po, packages/wp-plugin/essentials/languages/ionos-essentials.pot
linted all source files
I have
=> refactor: linted all sources files

packages/wp-plugin/essentials/inc/dashboard/blocks/vulnerability/class-wpscan.php, packages/wp-plugin/essentials/inc/dashboard/blocks/vulnerability/render.php
=> prevent missing wpscan token

packages/wp-plugin/essentials/inc/dashboard/blocks/whats-new/index.php, packages/wp-plugin/essentials/inc/dashboard/data/ionos/post_content.html, packages/wp-plugin/essentials/inc/dashboard/data/ionos/rendered-skeleton.html, packages/wp-plugin/essentials/inc/dashboard/index.php, packages/wp-plugin/essentials/languages/ionos-essentials-de_DE.po, packages/wp-plugin/essentials/languages/ionos-essentials-de_DE_formal.po, packages/wp-plugin/essentials/languages/ionos-essentials-en_US.po, packages/wp-plugin/essentials/languages/ionos-essentials-es_ES.po, packages/wp-plugin/essentials/languages/ionos-essentials-fr_FR.po, packages/wp-plugin/essentials/languages/ionos-essentials-it_IT.po, packages/wp-plugin/essentials/languages/ionos-essentials-nl_NL.po, packages/wp-plugin/essentials/languages/ionos-essentials-pl_PL.po, packages/wp-plugin/essentials/languages/ionos-essentials-sv_SE.po, packages/wp-plugin/essentials/languages/ionos-essentials.pot, packages/wp-plugin/essentials/src/dashboard/blocks/whats-new/block.json, packages/wp-plugin/essentials/src/dashboard/blocks/whats-new/edit.js, packages/wp-plugin/essentials/src/dashboard/blocks/whats-new/index.js
feature: Move whats new to a block to have translated strings.
=> feat(whats-new): create translatable but yet unstyled block

packages/wp-plugin/essentials/inc/dashboard/blocks/quick-links/config.php, packages/wp-plugin/essentials/languages/ionos-essentials-de_DE.po, packages/wp-plugin/essentials/languages/ionos-essentials-de_DE_formal.po, packages/wp-plugin/essentials/languages/ionos-essentials-en_US.po, packages/wp-plugin/essentials/languages/ionos-essentials-es_ES.po, packages/wp-plugin/essentials/languages/ionos-essentials-fr_FR.po, packages/wp-plugin/essentials/languages/ionos-essentials-it_IT.po, packages/wp-plugin/essentials/languages/ionos-essentials-nl_NL.po, packages/wp-plugin/essentials/languages/ionos-essentials-pl_PL.po, packages/wp-plugin/essentials/languages/ionos-essentials-sv_SE.po, packages/wp-plugin/essentials/languages/ionos-essentials.pot, packages/wp-plugin/essentials/src/dashboard/blocks/quick-links/quicklinks-style.scss
=> GPHWPP-3823_buttons-only-clickable-on-text

docs/7-release.md
=> fix: update release documentation to clarify pre-release and release process

.env, packages/wp-plugin/ionos-essentials/inc/dashboard/blocks/quick-links/config.php, packages/wp-plugin/ionos-essentials/inc/dashboard/blocks/whats-new/index.php, packages/wp-plugin/ionos-essentials/inc/tenants/config/ionos.php, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-de_DE.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-de_DE_formal.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-en_US.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-es_ES.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-fr_FR.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-it_IT.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-nl_NL.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-pl_PL.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-sv_SE.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials.pot
This pr changes english string according to https://docs.google.com/spreadsheets/d/1SYNiZ3Bk1pJBIbW9dpexcb5MlYqHd74ZNe91Dy0-JVY/edit?gid=1528279907#gid=1528279907 in the files.
There with green background: means checked.
=> New  strings and translation

packages/wp-plugin/ionos-essentials/inc/dashboard/blocks/deep-links/index.php
=> update default option result to ionos

packages/wp-plugin/ionos-essentials/inc/dashboard/blocks/next-best-actions/class-nba.php, packages/wp-plugin/ionos-essentials/inc/dashboard/blocks/next-best-actions/index.php, packages/wp-plugin/ionos-essentials/inc/dashboard/tests/phpunit/ClassNBATest.php
=> Fix NBA dismiss

.env.local.example
Updates the `.env.local.example` file with a more precise snippet to on how to use environment `BUILD_UP_TO_DATE` in a more flexible manner.
I have
=> Update env local

scripts/release.sh
=> Fix/release.sh : show stdout/stderr of commands

packages/wp-plugin/ionos-essentials/inc/dashboard/index.php
=> fix_iframe_resizing_for_responcive_view

packages/wp-plugin/ionos-essentials/inc/dashboard/blocks/banner/index.php
=> remove debug code

.gitignore
added `.go-waas.env` to `./gitignore`
=> chore: add .go-waas.env to .gitignore

packages/wp-plugin/ionos-essentials/inc/dashboard/blocks/banner/index.php, packages/wp-plugin/ionos-essentials/inc/dashboard/blocks/next-best-actions/class-nba.php, packages/wp-plugin/ionos-essentials/inc/dashboard/blocks/next-best-actions/index.php, packages/wp-plugin/ionos-essentials/inc/dashboard/index.php, packages/wp-plugin/ionos-essentials/inc/tenants/config/ionos.php, packages/wp-plugin/ionos-essentials/src/dashboard/blocks/deep-links/deeplinks-style.scss, packages/wp-plugin/ionos-essentials/src/dashboard/blocks/next-best-actions/style.css, packages/wp-plugin/ionos-essentials/src/dashboard/blocks/quick-links/quicklinks-style.scss
all commits can either go into the release or not. @peperuda-dev please decide what you like and what should go into the release
=> last minute changes

packages/wp-plugin/ionos-essentials/languages/ionos-essentials-fr_FR.po
=> Update fr translations

scripts/wp-env-after-start.sh
execution of wp-dev configuration in wp-env-after-start script will now take 2-3 seconds instead of 18-20 seconds.
=> fix: improve startup time by executing wp-dev config commands in bulk instead of separate pnpm exec wp-env commands

packages/wp-plugin/ionos-essentials/inc/dashboard/data/ionos/rendered-skeleton.html, packages/wp-plugin/ionos-essentials/inc/dashboard/data/twentytwentyfive-global-styles.json, packages/wp-plugin/ionos-essentials/src/dashboard/blocks/banner/banner-style.scss
Made several styling changes on banner, logo and banner buttons.
Please, test on WP 6.7 and 6.8 if whole dashboard looks good before approving.
=> update banner, buttons and logo

packages/wp-plugin/ionos-essentials/inc/dashboard/data/ionos/post_content.html, packages/wp-plugin/ionos-essentials/inc/dashboard/data/ionos/rendered-skeleton.html, packages/wp-plugin/ionos-essentials/inc/dashboard/data/twentytwentyfive-global-styles.json
=> fix(dashboard): min height for logos

packages/wp-plugin/ionos-essentials/languages/ionos-essentials-es_ES.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-es_MX.po
=> chore(i18n): tenant feedback

packages/wp-plugin/ionos-essentials/inc/dashboard/blocks/next-best-actions/class-nba.php
=> redirect logo-upload to header

.github/workflows/release.yaml, scripts/release.sh
check after next release if working under live conditions
=> feat(release): upload latest.zip to S3

packages/wp-plugin/ionos-essentials/languages/ionos-essentials-de_DE.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-de_DE_formal.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-en_US.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-es_ES.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-es_MX.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-fr_FR.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-it_IT.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-nl_NL.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-pl_PL.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-sv_SE.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials.pot, scripts/build.sh
=> feat((i18n): strip line numbers from pot and po files

phpunit/wp-tests-config.php, scripts/test.sh, scripts/wp-env-after-start.sh
=> Script fixes

packages/wp-plugin/ionos-essentials/inc/dashboard/blocks/next-best-actions/index.php
fix rest url due to failed refactoring
=> refactor rest url

packages/wp-plugin/ionos-essentials/inc/security/index.php, packages/wp-plugin/ionos-essentials/inc/security/pel/index.php, packages/wp-plugin/ionos-essentials/inc/security/ssl/index.php, packages/wp-plugin/ionos-essentials/inc/security/ssl/script.js, packages/wp-plugin/ionos-essentials/inc/security/style.css, packages/wp-plugin/ionos-essentials/inc/security/wpscan/index.php, packages/wp-plugin/ionos-essentials/inc/security/xmlrpc/index.php, packages/wp-plugin/ionos-essentials/ionos-essentials.php
=> Implement security feature

packages/docker/ecs-php/ruleset.xml
improve linting rules
try lint and lint-fix for php.
should work and not give any false "fixable" errors that dont get fixed.
=> update lint ruleset to avoid unfixable errors

packages/wp-plugin/ionos-essentials/inc/dashboard/blocks/quick-links/config.php, packages/wp-plugin/ionos-essentials/inc/dashboard/blocks/welcome/index.php, packages/wp-plugin/ionos-essentials/inc/dashboard/dashboard.css
Changes requested and tested by Ash
=> improve layout in welcomebox

packages/wp-plugin/ionos-essentials/inc/security/ssl.php
streamlined ionos security feature ssl
=> refactor: simplify ionos security ssl feature

packages/wp-plugin/ionos-essentials/inc/security/credentials-checking.php
simplify / streamline ionos security feature password checking php code
=> refactor(security): improve password checking php code

packages/wp-plugin/ionos-essentials/inc/maintenance_mode/index.php
Fixes the bug wit the yellow thing in frontend
=> add yellow button to frontendview

packages/wp-plugin/ionos-essentials/inc/security/pel.php
simplified pel feature of ionos security
=> refactor: simplify ionos security pel feature

package.json, pnpm-lock.yaml
=> updated stylelint dependency

packages/wp-plugin/ionos-essentials/inc/dashboard/index.php, packages/wp-plugin/ionos-essentials/inc/wpscan/controller/class-wpscan.php, packages/wp-plugin/ionos-essentials/inc/wpscan/index.php, packages/wp-plugin/ionos-essentials/inc/wpscan/tests/phpunit/ClassWPScanTest.php
- done some linting
- the method maybe_send_mail must be public to be tested
Introduced two unittests
- is the middleware data correclty converted
- is the sending of the email triggered if new vulns are found
=> introduce wpsan unit tests

packages/wp-plugin/ionos-essentials/inc/dashboard/blocks/welcome/index.php, packages/wp-plugin/ionos-essentials/inc/migration/index.php, packages/wp-plugin/ionos-essentials/inc/security/index.php, packages/wp-plugin/ionos-essentials/inc/security/security.js, packages/wp-plugin/ionos-essentials/inc/security/ssl.php
Show adminnotice, if security was uninstalled by essentials migration
=> add security migrated admin notice

packages/wp-plugin/ionos-essentials/inc/dashboard/dashboard.js, packages/wp-plugin/ionos-essentials/inc/dashboard/index.php, packages/wp-plugin/ionos-essentials/inc/dashboard/tabs/tools.php
- User can descide, which dashboard is the default dashboard
- defaults to our dashbard
=> add default dashboard button

packages/wp-plugin/ionos-essentials/languages/ionos-essentials-de_DE.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-de_DE_formal.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-en_US.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-es_ES.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-es_MX.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-fr_FR.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-it_IT.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-nl_NL.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-pl_PL.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-sv_SE.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials.pot
=> update po files

packages/wp-plugin/ionos-essentials/inc/dashboard/blocks/whats-new/index.php
needed, because on main the feature was implemented differently
=> add survey urls

scripts/wp-env-after-start.sh
=> add option for brand menu at startup

.secrets.example, packages/wp-plugin/ionos-essentials/inc/dashboard/blocks/vulnerability/index.php, packages/wp-plugin/ionos-essentials/inc/dashboard/dashboard.css, packages/wp-plugin/ionos-essentials/inc/dashboard/tabs/tools.php, packages/wp-plugin/ionos-essentials/inc/migration/index.php, packages/wp-plugin/ionos-essentials/inc/security/credentials-checking.php, packages/wp-plugin/ionos-essentials/inc/security/views/password-reset-necessary.php, packages/wp-plugin/ionos-essentials/inc/wpscan/controller/class-wpscan.php, packages/wp-plugin/ionos-essentials/inc/wpscan/controller/class-wpscanmiddleware.php, scripts/wp-env-after-start.sh
=> Minor bugfixes

packages/wp-plugin/ionos-essentials/inc/maintenance_mode/maintenance.js
Small change, no js error. Pretty much self explanatory
=> fix js maintenance

packages/wp-plugin/ionos-essentials/inc/descriptify/README.md, packages/wp-plugin/ionos-essentials/languages/README.md
=> feat: add README files for Descriptify and translation process

packages/wp-plugin/ionos-essentials/inc/dashboard/exos-themes/README.md, packages/wp-plugin/ionos-essentials/inc/dashboard/exos-themes/arsys.css, packages/wp-plugin/ionos-essentials/inc/dashboard/exos-themes/strato.css, packages/wp-plugin/ionos-essentials/inc/dashboard/view.php
Introduce exos theming
See it live here
https://wordpresstitle-u30i0o4k3r.live-website.com/wp-admin/admin.php?page=strato#overview
=> Exos theming

packages/wp-plugin/ionos-essentials/inc/dashboard/exos-themes/README.md, packages/wp-plugin/ionos-essentials/inc/dashboard/index.php, packages/wp-plugin/ionos-essentials/inc/dashboard/view.php
just two calls that were added through other branches while refactoring
=> refactor: get tenant name from singleton always

packages/wp-plugin/ionos-essentials/inc/security/index.php, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-de_DE.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-en_US.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-es_ES.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-es_MX.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-fr_FR.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-it_IT.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-nl_NL.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-sv_SE.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials.pot
=> fix textdomain

packages/wp-plugin/ionos-essentials/ionos-essentials/inc/dashboard/dashboard.css
=> fix(wpscan): load wpscan stylesheet

.github/PULL_REQUEST_TEMPLATE.md
_If the ui was changed by PR please provide a screenshot_
_Please replace this line with instructions on how to test your changes_
=> chore(pr-template): bring dod into PR template

packages/wp-plugin/ionos-essentials/ionos-essentials/inc/dashboard/index.php
wenn es keine recommends oder kritischen probleme gibt,setzen wir den wert auf null
-- Reviewer --
[ x ] LGTM
=> initialize all issues-categories

.changeset/funky-peanut-unicorn.md, .changeset/tricky-jars-make.md, packages/docker/ecs-php/composer.lock, packages/docker/potrans/composer.lock, packages/docker/rector-php/composer.lock, packages/wp-plugin/ionos-essentials/CHANGELOG.md, packages/wp-plugin/ionos-essentials/ionos-essentials.php, packages/wp-plugin/ionos-essentials/package.json
revert release commit and update incorrect changesets
=> Release 1.3.0 (fix)

packages/wp-plugin/ionos-essentials/ionos-essentials/inc/dashboard/blocks/site-health/index.php
_If the ui was changed by PR please provide a screenshot_
_Please replace this line with instructions on how to test your changes_
=> fix(overview): show maintenance label without reload

packages/wp-plugin/ionos-essentials/ionos-essentials.php, packages/wp-plugin/ionos-essentials/ionos-essentials/inc/class-tenant.php, packages/wp-plugin/ionos-essentials/ionos-essentials/inc/dashboard/blocks/my-account/index.php
_If the ui was changed by PR please provide a screenshot_
_Please replace this line with instructions on how to test your changes_
=> Fix language loading
