IONOS-WordPress/ionos-wordpress

.githooks/pre-commit, .nano-staged.mjs, README.md, package.json, pnpm-lock.yaml, scripts/_prepare.sh, scripts/release.sh
this feature adds automatic lint-fix execution on all staged files during `git commit`.
It will only operate on staged files.
Eventually fixed files will automatically be part of the commit.
You can disable this behavior by adding `--no-verify` to the git command. 
Example: 
- `git commit` will automatically execute lint-fix 
- `git commit --no-verify` will disable automatically execution of lint-fix 
This feature is automatically installed on `pnpm install`
=> feat: add pre-commit hook for automatic lint-fix

.github/shared/actions/devcontainer-shell-run/action.yaml, .github/workflows/build-devcontainer-image.yaml, .github/workflows/integration.yaml, .github/workflows/release.yaml
integrate prebuild devcontainer images into GitHub workflows.
devcontainer images will be build and reused in workflows.
previously devcontainer images where build again for every build step again.
furthermore pipelines visualization is now more finegrained
workflows run perfectly fine (see https://github.com/lgersman/ionos-wordpress/tree/refactor/speedup-github-workflows)
=> Refactor GitHub workflows

scripts/test.sh
if e2e test suite doesn't find the right playwright chromium path it expects 
the test script will output instructions how to fix this issue
=> fix: validate single chromium installation for Playwright environment setup

.vscode/extensions.json
add missing xdebug extension to vscode recommended extensions
=> chore: add xdebug.php-debug extension to VSCode configuration

packages/wp-plugin/essentials/.distignore
the README.md in dashboard feature folder should not be distributed in the plugin archive.
This PR adds the file to the `.distignore` file of the essentials plugin
=> fix: add README.md to .distignore to prevent it from being included in the essentials plugin archive

.prettierignore, .vscode/extensions.json, .vscode/tasks.json, eslint.config.mjs, scripts/lint.sh
- linter summary output in terminal
[lint-summary.webm](https://github.com/user-attachments/assets/0f81414b-69d7-4399-94dd-7c776f43e596)
- vscode problems view integration 
[vscode-tasks.webm](https://github.com/user-attachments/assets/a77ec5fd-6b3e-4165-8bf3-ee81c45cf36a)
=> integrate linter output with vscode problems panel and provide linter summary at end of lint/lint:fix output

.github/PULL_REQUEST_TEMPLATE.md
the template contents will be automatically inserted into the description field of newly created pull requests and can be freely edited.
it helps 
- developers by providing a checklist of thing to be done when preparing code for the pull requests
- reviewers to get a clue what the pr does and what to test
=> feat: add pull request template to standardize submission process

scripts/start.sh, scripts/test.sh, scripts/wp-env-after-start.sh
This pr fixes the sometimes occurring "permission denied" issue when doing `pnpm destroy`
I have
=> fix: copy phpunit file config into wp-env container

packages/docker/ecs-php/ecs-config.php, packages/docker/rector-php/rector-config-php7.4.php, packages/wp-plugin/essentials/inc/migration/index.php, packages/wp-plugin/essentials/inc/migration/tests/phpunit/MigrationTest.php, scripts/build.sh, scripts/test.sh
This pr fixes rector downgrade transpilation by providing the WordPress API to Rector.
The `pnpm test` command was improved by testing all downgraded plugin versions to be syntax compatible to the target php version.
I have
=> fix: GPHWPP-3806 rector problems 

packages/wp-plugin/essentials/inc/dashboard/blocks/quick-links/render.php, packages/wp-plugin/essentials/inc/dashboard/blocks/welcome/index.php, packages/wp-plugin/essentials/src/dashboard/blocks/welcome/view.js
changes:
- any user with an id should dismiss his welcome block, not restricted to any permission imho
- nonce not required, X-WP-Nonce automatically set by wp-api-fetch
- persist also when clicked outside
=> code review improvements

docs/6-forking.md, scripts/release.sh
Fixes wrong url's pointing to a lgersman's fork in notification messages. 
I have
=> Fix release script by replacing static github lgersman ref to dynamic github-repo-name

packages/wp-plugin/ionos-essentials/inc/dashboard/index.php
Remove Blank space on the left side, when on mobile view.
- Related Issue #
- Closes #
I have
Checkout branch and verify that issue is fixed.
=> fix space on open mobile wp-menu

packages/wp-plugin/ionos-essentials/inc/update/index.php, packages/wp-plugin/ionos-essentials/ionos-essentials.php, scripts/release.sh
pr introduces the `info.json` feature. 
this file will be used to transport version,slug, changelog and download url of the latest release.
benefits of the pr are : 
- plugin update mechanism could be massively simplified
- we can track (then) download statistics using plain curl per asset (aka plugin version) 
you can test it in this fork `curl -i https://api.github.com/repos/lgersman/ionos-wordpress/releases -H "Accept: application/vnd.github.manifold-preview+json"`
=> github rest api free update mechanism 

packages/wp-plugin/ionos-essentials/languages/ionos-essentials-de_DE.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-de_DE_formal.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-en_US.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-es_ES.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-es_MX.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-fr_FR.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-it_IT.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-nl_NL.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-pl_PL.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials-sv_SE.po, packages/wp-plugin/ionos-essentials/languages/ionos-essentials.pot, scripts/build.sh
an attempt to remove duplicate comments from po files. they are left after we remove the line numbers and will be removed by lint-fix:i18n / deepl / potrans
if there is an easier way to achieve the same in bash, feel free to suggest :)
=> fix(i18n): remove duplicate comments

packages/docker/ecs-php/ecs-config.php
since we have no more global variables in our `config.php` files we can reenable strict global variable override sniff.
=> refactor: reenable strict GlobalVariablesOverrideSniff

.env, README.md, docs/5-test.md, packages/wp-plugin/ionos-essentials/inc/dashboard/tabs/tools.php, packages/wp-plugin/ionos-essentials/inc/jetpack-flow/index.php, packages/wp-plugin/ionos-essentials/inc/security/tests/e2e/security.spec.js, playwright.config.js, scripts/test.sh, scripts/wp-env-after-start.sh
=> set password defined in environment variable WP_PASSWORD (declared in .env) as admin password for all wp-env wp containers

packages/wp-plugin/ionos-essentials/inc/security/xmlrpc.php
skips running ip4 and ip6 tests if xmlrpc methods are already disabled.
=> fix: add early return after_disable_xmlrpc_methods

packages/docker/ecs-php/ecs-config.php, packages/docker/ecs-php/ruleset.xml
yoda or not - both options are valid and neither is preferred by lint or lint-fix
=> chore(lint): no yoda conditions

packages/wp-plugin/ionos-essentials/inc/dashboard/index.php
Sonst geht das bei UDAG nicht, weil das dort nicht zufällig gleich ist.
=> use brand as slug

packages/wp-plugin/ionos-essentials/inc/dashboard/blocks/next-best-actions/index.php
fixes an error when php and wordpress version are too old. found the bug on stretch monster space with an older wordpress version, that doesnt have the polyfill for the php function.
=> fix(essentials): replace array_all for more compatibility

packages/wp-plugin/ionos-essentials/inc/descriptify/index.php
without that fix, HTML-Tags are print out, not the real link
issue was introduced may, 8th: https://github.com/IONOS-WordPress/ionos-wordpress/pull/317
=> do not show HTML-Tags on page

packages/wp-plugin/ionos-essentials/inc/security/credentials-checking.php
while changing personal user settings, a password check is performed. if the password is unchanged, it es empty, which results in "leaked". 
With that fix, the user can change his or her settings again, regardless of the password.
=> fix: ensure password fields are not empty before comparison

packages/wp-plugin/ionos-essentials/inc/wpscan/controller/class-wpscan.php, packages/wp-plugin/ionos-essentials/inc/wpscan/controller/class-wpscanmiddleware.php
if middleware says: plugin not found (that is with all plugins not checked by wpscan, that come from a third party source), resonse is: "Go ahead, install"
=> if plugin not found, pass

packages/wp-plugin/ionos-essentials/inc/migration/index.php
deleting the plugin right away (in the admin_init hook) resulted in a fatal error because the files were not found.
migration still worked but only on the second run.
=> fix(migration): move plugin deletion to shutdown action
